images:
  go-app.development:
    image_version_arg_key: GO_VERSIONS
    versions:
      - version: "1.26.1"
        latest: true
      - version: "1.25.8"
    architectures:
      - platform: linux/amd64
        runner: ubuntu-26.04
      - platform: linux/arm64
        runner: ubuntu-26.04-arm
  node-webapp.development:
    image_version_arg_key: NODE_VERSION
    versions:
      - version: "24"
        latest: true
      - version: "22"
      - version: "20"
    architectures:
      - platform: linux/amd64
        runner: ubuntu-26.04
      - platform: linux/arm64
        runner: ubuntu-26.04-arm
  rust-app.development:
    image_version_arg_key: RUST_VERSION
    versions:
      - version: "1.98.0"
        latest: true
    architectures:
      - platform: linux/amd64
        runner: ubuntu-26.04
      - platform: linux/arm64
        runner: ubuntu-26.04-arm
